### ISSUE TITLE
Stacktrace when directory is missing write permission

### ISSUE THREAD

**Issue by wdiestel** [nicos-angelopoulos/prosqlite#1]
I got a stacktrace during a number of updates on a database, where the database file itself had write permission, but the directory where it resides, had only read and execute permissions. Not sure why write permissions on the directory itself are necessary, but in any case a sound error message would help users to understand the problem. I could not understand the reason from the stacktrace alone, it was just try&error to find the root cause.

```
SWI-Prolog [thread 1 (main) at Fri Jan 21 19:30:01 2022]: received fatal signal 11 (segv)
C-stack trace labeled "crash":
  [0] save_backtrace() at :? [0x7fc275cbfd76]
  [1] print_c_backtrace() at :? [0x7fc275cbfe1a]
  [2] sigCrashHandler() at :? [0x7fc275cbff17]
  [3] killpg() at ??:? [0x7fc275a7ed60]
  [4] get_query_string() at ??:? [0x7fc275422fa3]
  [5] PL_next_solution___LD.cold() at pl-wam.c:? [0x7fc275c2f7c0]
  [6] query_loop() at :? [0x7fc275d04fba]
  [7] prologToplevel() at :? [0x7fc275d04e4b]
  [8] /usr/bin/swipl(+0x10b4) [0x55ddcd5680b4]
  [9] __libc_start_main() at ??:? [0x7fc275a69d0a]
  [10] /usr/bin/swipl(+0x10fa) [0x55ddcd5680fa]
Prolog stack:
  [146] prosqlite:c_sqlite_query/3 [PC=1 in supervisor]
  [143] system:<meta-call>/1 [PC=13 in clause -1]
  [142] system:once/1 [PC=3 in clause 1]
  [141] db_redaktantoj:editor_update/2 [PC=56 in clause 1]
```

I used the docker image swipl:stable

```
$ swipl 
Welcome to SWI-Prolog (threaded, 64 bits, version 8.4.1)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit https://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

?- pack_info(prosqlite).
Package:                prosqlite
Title:                  An SWI-Prolog interface to SQLite
Installed version:      1.6
Installed in directory: /usr/share/swi-prolog/pack/prosqlite
Author:                 Nicos Angelopoulos <http://stoics.org.uk/~nicos>, Sander Canisius <http://bioinformatics.nki.nl/~canisius>
Maintainer:             Nicos Angelopoulos <http://stoics.org.uk/~nicos>
Packager:               Nicos Angelopoulos <http://stoics.org.uk/~nicos>
Home page:              http://stoics.org.uk/~nicos/sware/prosqlite
Download URL:           http://stoics.org.uk/~nicos/sware/packs/prosqlite/prosqlite-*.tgz
Provided libraries:     prosqlite

```

**Comment by nicos-angelopoulos** [comment]
Dear wdiestel,

Thanks for you comment. 

Strictly speaking it is the responsibility of the programmer to make sure  the file can be created. 

However, having a more informative message is preferable.
I added a call to open/3 that will generate a message such as:
ERROR: No permission to open source_sink `simple.sqlite' (Permission denied)
ERROR: In:
ERROR:   [13] open(simple.sqlite,write,_38480)
...

You can update your installation by simply copying the "prolog/prosqlite.pl" file from
github onto your local installation. 

Or by updating the install to the newly published 1.7 from the SWI server.

Regards,

Nicos Angelopoulos
https://stoics.org.uk/~nicos
