### ISSUE TITLE
NULL handling doesn't work fully; translates to '' on read but doesn't match queries

### ISSUE THREAD

**Issue by JBThiel** [nicos-angelopoulos/prosqlite#4]
Bug with NULL handling, seen when using as_predicates(true).
On reading it converts NULL to '' and puts in the variable, which is fine and usable.
However, it's not matching '' to NULL, if you use the predicate in a query manner.
ie. if the table predicate variable is already bound to '', then the predicate won't match when the field holds NULL.
So:
mytable(A,B,C) works, sets the variables to '' for any NULLs
mytable(A,B,'') will fail to match any rows holding NULL in the 3rd field

ie. the problem is if you want/have NULLs in the data, and need to query match on them.

== ODBC
I noticed the SWIPL ODBC module handles nulls with special atom '$null$', or null(_),
or a user-settable null(NullSpecifier) option
https://www.swi-prolog.org/pldoc/doc_for?object=section(%27packages/odbc.html%27)

I tried, but these don't work in Prosqlite.
The prosqlite source code has some fixme notes on null handling, so maybe you were planning to add that.

Workaround
A potential workaround for now is ensure that a field that needs to be queryable has no NULLs, for example via setting DEFAULT '' for the field.

**Comment by nicos-angelopoulos** [comment]
Thanks for reporting. Added better support for nulls. Not sure their are caught in all places, but 
they should now return '$null$' and that value should also work in predicated, partial instantiated query calls.

?- ex_t(A,B,C), write(A:B:C), nl, fail.
1:v12:v13
2: : $null$
3: $null$ : w
false.

?- ex_t(A,B,'$null$')
|    .
exf3- $null$
A = 2,
B = '' ;
false.
