### ISSUE TITLE
Exception with matching on field named "group" (and probably other special keywords)

### ISSUE THREAD

**Issue by JBThiel** [nicos-angelopoulos/prosqlite#5]
Seems to be a problem if a table has fields with name collisions on SQL keywords.
Or at least "group", which is where I note the error, but I speculate it might be other keywords too.  A general escaping/quoting issue.

Example:
With a table with 3rd field named "group", then attempting to match a predicate like
?- mytable(A,B,groupaa).
ERROR: Unhandled exception: Unknown message: sqlite_error(1,'near "group": syntax error')

(i.e. 'groupaa' is a value in the field named 'group').

When I rename the field to "group1", then it works ok.

Sqlite allows table fields with names like "group", so ProSqlite should too.

The error should be easy to reproduce. If not, let me know, and I will try to work up an exact demo sequence.

**Comment by nicos-angelopoulos** [comment]
Thanks for reporting. Using keywords for field/column names seems rather risky. 
However, made some changes so the specific query now works. 
Not sure all cases where a keyword is implicated are covered.
