### ISSUE TITLE
prosqlite.so shared lib not loaded/accessible in standalone exe (Swipl) [SOLVED] [WORKAROUND]

### ISSUE THREAD

**Issue by JBThiel** [nicos-angelopoulos/prosqlite#6]
The prosqlite.so library is not accessible or loaded correctly when compiling a standalone exe with SWI-Prolog.
As testable by sqlite_binary_version/2  will fail, you don't even need to open a db.

I have debugged and believe solved:
It appears related to prosqlite.pl loads the library via
:- load_foreign_library(foreign(prosqlite)).
Instead of the recommended
:- use_foreign_library(foreign(prosqlite)).

I presume use_foreign_library does some additional registration which load_foreign_library omits, that is needed when the exe compiler  (qsave_program, etc) is collecting the needed library references.
(This might also be some bug in Swipl, maybe load_foreign should work equally well? testing on version 9.1.2)

The SOLUTION is to alter the line in prosqlite.pl as follows:
```
@@ -26,7 +26,7 @@
 :- at_halt( sqlite_disconnect ).

 :- use_module(library(shlib)).
-:- load_foreign_library(foreign(prosqlite)).
+:- use_foreign_library(foreign(prosqlite)).

 :- dynamic(sqlite_connection/3).
 :- dynamic(sqlite_db:sqlite_asserted/4).

```

I also found a WORKAROUND for programs using the stock Prosqlite 1.8: 
In the program code, put an explicit use_foreign_library call BEFORE the use_module call.
Like this:
```
:- use_foreign_library(foreign(prosqlite)).
:- use_module(library(prosqlite)).

```

Here is a test program and Make recipe.
In the failure case, you don't get the output from sqlite_binary_version, but an error:
```
Calling sqlite_binary_version/2 ...
ERROR: -g user:main: false

```

MAKE
```
exepro: exeprosqlite.pl
  swipl  --foreign=save --goal=main --stand_alone=true -o exepro -c exeprosqlite.pl

```
TEST PROGRAM (exeprosqlite.pl)
```
% WORKAROUND: with the stock 1.8 prosqlite, which does load_foreign_library instead of use_foreign_library
%   if explicitly put this use_foreign BEFORE the module invoke, then it works.
% So this is an alternate solution if a user can't update the pack.
% There is presumably something in Swipl internals of use_foreign, that registers the library
%   so it's handled correctly for standalone executable
%   and load_foreign doesn't do that (perhaps it should? a swipl bug?)
%:- use_foreign_library(foreign(prosqlite)).
:- use_module(library(prosqlite)).

main :-
  % Testing... These are NOT sufficient at this point to workaround the load_foreign_library bug in stock Prosqlite 1.8
  % reload_foreign_libraries,
  % load_foreign_library(foreign(prosqlite)),
  % use_foreign_library(foreign(prosqlite)),

  % Collect and show current foreign libs
  findall(L, current_foreign_library(L,_),Ls),
  write("LIBS: "), writeln(Ls),

  % Test call into prosqlite.so
  writeln("Calling sqlite_binary_version/2 ..."),
  % This pred is sufficient to test if we can find/call the backing C library
  sqlite_binary_version(V1,V2),
  writeln("... call succeeded"),
  format("Sqlite Binary Version: ~w, Date: ~w~n", [V1,V2]).

```

**Comment by nicos-angelopoulos** [comment]
Thanks for spotting this. Pushed the change.
