### ISSUE TITLE
Abolish/2 in sqlite_clean_up_predicated_for/2 disrupts MAKE/0 facility in Swipl

### ISSUE THREAD

**Issue by JBThiel** [nicos-angelopoulos/prosqlite#7]
Current code is
```
sqlite_clean_up_predicated_for( Conn, pam(Pname,Arity,Mod) ) :-
     % functor( Head, Pname, Arity ),
     % retractall( Mod:Head ),
     abolish( Mod:Pname, Arity ),
     retractall( sqlite_db:sqlite_asserted(Conn,Pname,Arity,Mod) ).

```

The abolish/2 call removes the dynamic attribute.  This results in considerable warnings if using the MAKE/0 facility in Swipl, along with the as_predicates(true) feature of Prosqlite, because Make will warn about all the uses of the predicates in the program code. Like this:
```
?- make.
Warning: The predicates below are not defined. If these are defined
Warning: at runtime using assert/1, use :- dynamic Name/Arity.
{... all the dynamic table predicate usages ... }
```

Typically, with the as_predicates feature, you have the predicates defined in a leading :- dynamic ...  directive, with many calls to them in the program code.
After a connect/disconnect cycle, Prosqlite abolish/2 is removing the dynamic property, thus giving the warnings on subsequent make.

The commented functor/retractall combo (already in the Prosqlite code) effectively does the same result of removing the predicates, but keeps them marked as dynamic.  So make/0 will reload without warnings, thus a better approach?
I'm testing the functor/retractall combo instead of abolish, and it seems to be working so far.

Is there a reason abolish/2 was necessary here?  If not, functor/retractall would be preferred to preserve the dynamic property for make/0.

Another possibility: Prosqlite could re-set the dynamic property explicitly after abolish/2 via
dynamic(Preds, Options) call, as provided by Swipl (but not all Prologs?).

This can also be done in the user program as a workaround, but it's clumsy/unexpected to have to reset the property for all your tables, when you've already set it near the top with a   :- dynamic   directive.

**Comment by nicos-angelopoulos** [comment]
This is not really a pack(prosqlite) issue. It has to do more with MAKE in SWI. 
Maybe best to start a discussion in their users forum, usually prosqlite contributes to those.

The current implementation in prosqlite seems correct. You want to abolish the preds in case you want to reload the database. 

In any case, I have added  sqlite_disconnect/2 with option abolish_pred. 
You can use

    ?- sqlite_disconnect( db, abolish_pred(false) ). 

to get the behaviour you want.
